import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import type { MealPlan } from '@/types/mealPlan';

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

export function buildMealPlanHtml(params: {
  plan: MealPlan;
  diet: string;
  answers: Array<{ question: string; answer: string }>;
}): string {
  const preferenceItems = params.answers
    .map(
      (q) =>
        `<li><strong>${escapeHtml(q.question)}</strong>: ${escapeHtml(q.answer)}</li>`,
    )
    .join('');

  const daySections = params.plan.days
    .map(
      (day, index) => `
      <section class="day">
        <h2>${escapeHtml(day.name)}${index === 0 ? ' (today)' : ''}</h2>
        <h3>Breakfast</h3>
        <p>${escapeHtml(day.breakfast)}</p>
        <h3>Lunch</h3>
        <p>${escapeHtml(day.lunch)}</p>
        <h3>Dinner</h3>
        <p>${escapeHtml(day.dinner)}</p>
      </section>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>7-Day Meal Plan</title>
    <style>
      body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #111; padding: 24px; line-height: 1.45; }
      h1 { font-size: 24px; margin: 0 0 8px; }
      .meta { color: #555; margin-bottom: 20px; }
      h2 { font-size: 18px; margin: 0 0 8px; }
      h3 { font-size: 14px; margin: 12px 0 4px; }
      p { margin: 0 0 4px; }
      ul { padding-left: 18px; margin: 8px 0 20px; }
      .day { border-top: 1px solid #ddd; padding: 16px 0; page-break-inside: avoid; }
      footer { margin-top: 28px; color: #777; font-size: 12px; }
    </style>
  </head>
  <body>
    <h1>7-Day Meal Plan</h1>
    <p class="meta">Dietary filter: ${escapeHtml(params.diet)}</p>
    <h2>Your preferences</h2>
    <ul>${preferenceItems}</ul>
    ${daySections}
    <footer>Generated by Savor IQ</footer>
  </body>
</html>`;
}

export async function exportMealPlanPdf(params: {
  plan: MealPlan;
  diet: string;
  answers: Array<{ question: string; answer: string }>;
}): Promise<void> {
  const html = buildMealPlanHtml(params);
  const file = await Print.printToFileAsync({ html });

  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) {
    throw new Error('Sharing is not available on this device.');
  }

  await Sharing.shareAsync(file.uri, {
    mimeType: 'application/pdf',
    UTI: 'com.adobe.pdf',
    dialogTitle: 'Share meal plan PDF',
  });
}
